services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: project10_postgres

    environment:
      POSTGRES_USER: project10_user
      POSTGRES_PASSWORD: project10_password
      POSTGRES_DB: project10_agent

    ports:
      - "5435:5432"

    volumes:
      - project10_postgres_data:/var/lib/postgresql/data

volumes:
  project10_postgres_data: